### ISSUE TITLE
Adding entity that is a childEntity results in ServerError

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-db#20]
To reproduce, start a new project.
Add an entity, e.g. "events":
http://rs.tdwg.org/dwc/terms/Event
Add another entity, e.g. "samples":
http://rs.tdwg.org/dwc/terms/MaterialSample
Select checkbox (is a child entity).
Select parent entity "events"

Click Save Config...
Comes back with "Server Error Occurred" and it does not save.\

If i add the samples as NOT a child entity, it works fine.

**Comment by rodney757** [comment]
I can't reproduce.

When you add an entity, we auto add an Attribute, however the attribute doesn't have a column name.

Maybe you attempted to save before setting a column name?

This will be addressed when we re-work the project config ui
