### ISSUE TITLE
invalid duplicate materialSampleID error

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-db#26]
Reported from Michael Mahoney:
changing the eventid on a materialSampleID throws an error saying duplicate sampleID, error looks like:
Validation Results
Uploading...
Initializing...
Excel workbook filename = geome-fims-output-excel_minitest.xlsx
Validating...

Validation results on Samples worksheet, for entity: Sample.
1 or more errors found. Must fix to continue. Click each message for details
Error: Unique value constraint did not pass
"materialSampleID" column is defined as unique across the entire project but some values used more than once: "DUT_1159", "DUT_1158", "DUT_1156"
Error: Duplicate parent records
Duplicate "materialSampleID" values, however the other columns are not the same.

I was able to reproduce this error from the ground up:

Make a project that is a clone of the biocode configuration.
Create an eventid "unknown" along with a sampleID that points to it. Load data
Create another eventid "jd1". Load data.
In the sampleID metadata for the sample just created, change the eventid to point from "unknown" to the new eventid "jd1". Load data.

At this point the error is thrown.

**Comment by ewingrj** [comment]
fixed
