### ISSUE TITLE
Reload data option not working as expected

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-db#27]
Loaded to a biocode project..
had just "tissueInstitution" = "Unknown"
System created a tissue record as it should.
I wanted to replace this data so i removed the tissueInstitution='Unknown" field and checked the "reload data" and re-loaded the data.  However, the tissue record was still present with tissueInstitution="Unknown".
Temporary Work-around was to entirely delete the expedition and re-load data.

**Comment by ewingrj** [comment]
fixed in biocodellc/biocode-fims-commons@069dda3
