### ISSUE TITLE
Adding dateCreated and dateModified fields

### ISSUE THREAD

**Issue by steierj** [biocodellc/geome-db#63]
it would be useful for reporting purposes to have these two fields available to users of GEOME.

**Comment by jdeck88** [comment]
are these two fields data properties of Sample, Tissue, or Event?  Also, what exactly are we describing with these fields?  Is it date that the metadata was first uploaded into GEOME or modified in GEOME? or, is it the date a tissue was created from a sample?   Should the user enter a year, month, and day and in what format?

**Comment by OMahoneyM** [comment]
It was my hope that these fields would be generated as timestamps in the relational db when they are created and modified, respectively. I don't see the fields being user input, rather being appended to the end of worksheets like the bcid and projectID are when a user downloads project data. Is this possible?

**Comment by jdeck88** [comment]
Yeah, this is recorded on the backend and available in JSON (e.g. see https://api.geome-db.org/projects/255/expeditions/Costa-rica).  Mike mentions having this in the spreadsheet download... or would it be better to have it on the record detail on the website (e.g. https://geome-db.org/record/ark:/21547/DTc210882)? or, both places? @steierj @OMahoneyM

**Comment by OMahoneyM** [comment]
It would be most useful if it were included in the spreadsheet download. That said, I believe your api example shows the date created for the expedition and not for the samples. Does the backend record these values on the sample/event/tissue level?

**Comment by jdeck88** [comment]
Yes,  the finest modification date recorded is at the expedition level and does not track separate modification dates for individual records... this is in large part due to the fact most expeditions are replaced as entire spreadsheets with possible record modification scenarios including record deletion, deletion then re-creation, or modification.   this would make tracking individual record modification dates tricky.

**Comment by jdeck88** [comment]
Closing.. will not fix.
