### ISSUE TITLE
Update to Plate Viewer requested

### ISSUE THREAD

**Issue by steierj** [biocodellc/geome-db#66]
As per Stephanie Bush - 
Request ability to display 2-3 additional data fields per well in the GEOME plate viewer. The default display is materialSampleID, with the option to display ONE additional data field. Would prefer to keep the default but option to display 1, 2, or 3 additional data fields e.g. scientificName, phylum, subProject etc. 

Also, add a character to the current empty cell above the alphabetic row headers and to the left of the numerical column headers. This can then be copied and pasted into Excel.

<img width="1501" alt="geome plate viewer add another data field and " src="https://user-images.githubusercontent.com/74207845/203389014-d11977ea-d1eb-490f-ae21-63f3abe14b10.png">

**Comment by jdeck88** [comment]
This is complete... will be displayed with next deploymen t
