### ISSUE TITLE
Query of Sample_Photos failing

### ISSUE THREAD

**Issue by Tesserazoa** [biocodellc/geome-db#68]
For an expedition that has photos, among the "Child Entities" there is an ARK to Sample_Photos. But when one selects links labeled in the following form "Query All EXPEDITION-NAME Sample_Photos", the searches do not execute correctly. Searches for the other "Child Entities", such as fastqMetadatas, Tissues, etc. work just fine, so this appears to be restricted to Sample_Photos.

**Comment by jdeck88** [comment]
Ok, thanks, will check this out

**Comment by Tesserazoa** [comment]
John, I just noticed that similar searches for fasta files are also failing. Sorry I did not notice before.
--Allen

Allen G. Collins<http://invertebrates.si.edu/staff/collins.cfm>
Zoologist & Director of National Systematics Lab<https://www.fisheries.noaa.gov/about/national-systematics-laboratory> of NOAA Fisheries, Office of SCIENCE & TECHNOLOGY
Curator of Porifera, Medusozoa, Ctenophora for SMITHSONIAN INSTITUTION NATIONAL MUSEUM OF NATURAL HISTORY

  *   Phone: 202.633.0645 Emails: ***@***.******@***.***>; ***@***.******@***.***>
  *   Mail: Department of Invertebrate Zoology, Smithsonian National Museum of Natural History, MRC-163, P.O. Box 37012, Washington, D.C. 20013-7012 USA
  *   Courier Address: Smithsonian Institution, MR 0163, Natural History, West Loading Dock, 10th and Constitution Ave NW, Washington, D.C. 20560


From: John Deck ***@***.***>
Date: Thursday, April 20, 2023 at 11:10 AM
To: biocodellc/geome-db ***@***.***>
Cc: Collins, Allen ***@***.***>, Author ***@***.***>
Subject: Re: [biocodellc/geome-db] Query of Sample_Photos failing (Issue #68)
External Email - Exercise Caution

Ok, thanks, will check this out
